apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopping-ingress
  namespace: shopping-site
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: shopping.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopping-frontend-service
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: shopping-api-service
            port:
              number: 8080
